-- Esquema
DROP SCHEMA IF EXISTS EPUB_DIGITAL;
CREATE SCHEMA IF NOT EXISTS EPUB_DIGITAL;
USE EPUB_DIGITAL;

-- Tablas
CREATE TABLE LIBROS (
    id_libro INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    autor_id INT NOT NULL,
    categoria_id INT NOT NULL
);

CREATE TABLE USUARIOS (
    id_usuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL
);

CREATE TABLE AUTOR (
    id_autor INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT
);

CREATE TABLE PEDIDOS (
    Id_pedido INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha DATE NOT NULL,
    monto DECIMAL(10, 2) NOT NULL,
    id_libro INT NOT NULL,
    id_usuario INT NOT NULL
);

CREATE TABLE CATEGORIA (
    id_categoria INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- ALTERS

ALTER TABLE LIBROS
    ADD CONSTRAINT fk_autor_libro
    FOREIGN KEY (autor_id) REFERENCES AUTOR(id_autor),
    ADD CONSTRAINT fk_categoria_libro
    FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id_categoria);

ALTER TABLE PEDIDOS
    ADD CONSTRAINT fk_libro_pedido
    FOREIGN KEY (id_libro) REFERENCES LIBROS(id_libro),
    ADD CONSTRAINT fk_usuario_pedido
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario);
