INSERT INTO AUTOR(nombre, descripcion) VALUES
       ('Yuval Noah Harari', 'Yuval Noah Harari (24 de febrero de 1976, Kiryat Atta, Israel) es un profesor, historiador, filósofo y escritor israelí. Es conocido a nivel mundial por sus libros de historia.'),
       ('Carl Sagan', 'Carl Edward Sagan (Nueva York, 9 de noviembre de 1934-Seattle, 20 de diciembre de 1996) fue un astrónomo, astrofísico, cosmólogo, astrobiólogo, escritor y divulgador científico estadounidense.'),
       ('Cal Newport', 'Es profesor de Ciencias de la Computación en Georgetown University. Es autor de cinco libros y escribe el popular blog Study Hacks, que tiene como propósito descifrar los “códigos para ser exitoso” tanto en los estudios como en el trabajo.'),
       ('Stephen Hawking', 'Stephen Hawking fue un físico teórico, cosmólogo y autor, mejor conocido por sus trabajos científicos relacionados a la relatividad general y los hoyos negros, al igual que por distintos libros de ciencia popular que publicó a lo largo de su vida.'),
       ('Richard Dawkings', 'linton Richard Dawkins (Nairobi, 26 de marzo de 1941) es un biólogo evolutivo,​ etólogo, zoólogo y divulgador científico británico. Fue titular de la cátedra Charles Simonyi de Difusión de la Ciencia en la Universidad de Oxford hasta 2008.linton Richard Dawkins (Nairobi, 26 de marzo de 1941) es un biólogo evolutivo,​ etólogo, zoólogo y divulgador científico británico. Fue titular de la cátedra Charles Simonyi de Difusión de la Ciencia en la Universidad de Oxford hasta 2008.' ),
       ('Charles Darwin', 'Charles Darwin era un naturalista británico que propuso la teoría de la evolución biológica por selección natural. Darwin definió la evolución como "descendencia con modificación", la idea de que las especies cambian a lo largo del tiempo, dan origen a nuevas especies y comparten un ancestro común.'),
       ('Daniel Kahneman', 'Daniel Kahneman es un psicólogo social que recibió el Premio Nobel de Economía en el año 2002 “por tener ideas integradas desde la investigación psicológica en la ciencia económica, especialmente sobre el juicio humano y la toma de decisiones bajo incertidumbre”.'),
       ('Marco Aurelio', 'Marco Aurelio reinó como emperador romano desde el 161 al 180 EC, y es mejor conocido como el último de los Cinco Emperadores Buenos de Roma (después de Nerva, Trajano, Adriano y Antonino Pío) y como el autor de la obra filosófica Meditaciones.'),
       ('Friedrich Nietzsche', 'Friedrich Nietzsche (1844-1900) fue un notable y polémico filólogo y filósofo alemán autor de las obras Así habló Zaratustra, La voluntad de poder, El origen de la tragedia, Gaya Ciencia, Verdad y mentira en sentido extramoral, entre otras.'),
       ('Platon', 'Fue un filósofo ateniense del siglo V a.C., discípulo de Sócrates y maestro de Aristóteles. Fundó la Academia, donde impartió clases hasta el final de su vida. La condena a muerte de su maestro Sócrates influirá mucho en su vida y en sus obras.*'),
       ('Aristoteles', 'Aristóteles de Estagira (384-322 a.C.) fue un filósofo griego pionero en la examinación sistemática y científica de todas las áreas del conocimiento humano, conocido en su época como “el hombre que lo sabía todo” y luego simplemente como “el filósofo”, sin que fueran necesarios más calificativos debido a su fama.');

INSERT INTO CATEGORIA(nombre) VALUES
       ('Filosofia'),
       ('Economia'),
       ('Ciencia'),
       ('Biologia'),
       ('Productividad'),
       ('Historia'),
       ('Ficcion');

INSERT INTO EDITORIALES (nombre, contacto) VALUES
       ('Debate', 'contacto@Debate.com.ar'),
       ('Planeta Argentina', 'contacto@planeta.com.ar'),
       ('Grupo Editorial Norma', 'contacto@norma.com.ar'),
       ('Ivrea', 'contacto@ivrea.com.ar'),
       ('Siglo XXI', 'contacto@sigloxxi.com.ar'),
       ('Losada', 'contacto@losada.com.ar'),
       ('Salvat ciencia', 'contacto@salvatciencia.com.ar'),
       ('Alción', 'contacto@alcioneditora.com.ar'),
       ('Gradifco', 'contacto@gradifco.com.ar'),
       ('Paidós', 'contacto@paidosargentina.com.ar'),
       ('Critica', 'contacto@Critica.com.ar'),
       ('Poseidon', 'contacto@poseidoneditorial.com.ar'),
       ('Gradifico', 'contacto@editorialgradifico.com.ar'),
       ('Oceano', 'contacto@oceanolibros.com.ar'),
       ('Del oeste', 'contacto@deloeste.com.ar');


INSERT INTO LIBROS (nombre, autor_id, categoria_id, editorial_id) VALUES
       ('Cosmos', 2, 3, 2),
       ('Sapiens: De Animales a Dioses', 1, 6, 1),
       ('Homo Deus', 1, 6, 1),
       ('21 lecciones para el siglo 21', 1, 6, 1),
       ('Una breve historia del tiempo', 4, 3, 11),
       ('La teoria del todo', 4, 3, 11),
       ('El universo en una Cascara de Nuez', 4, 3, 11),
       ('Breves respuestas a las grandes preguntas', 4, 3, 11),
       ('El origen de las especies', 6, 4, 13),
       ('El Gen Egoista', 5,3, 7),
       ('Meditaciones', 8,1, 15),
       ('Asi Hablo Zaratustra', 9, 1, 12),
       ('La republica', 10, 1, 12),
       ('La etica', 11, 1, 12),
       ('El anitcristo', 9, 1, 12),
       ('Pensar Rapido, Pensar Despacio', 7, 2, 1),
       ('Enfocate', 3,5, 10),
       ('Minimalismo digital', 3, 5, 10);

INSERT INTO USUARIOS(user_name) VALUES
       ('user123'),
       ('coolcat22'),
       ('soccerfan88'),
       ('musiclover99'),
       ('gamerpro23'),
       ('bookworm47'),
       ('travelbug55'),
       ('foodiegirl78'),
       ('techwizard101'),
       ('artlover36'),
       ('fitnessfreak77'),
       ('fashionista25'),
       ('naturelover63'),
       ('moviebuff91'),
       ('adventureseeker82'),
       ('sciencegeek44'),
       ('beachbum72'),
       ('animallover57'),
       ('historybuff39'),
       ('dreamer98'),
       ('codingwhiz50'),
       ('DIYenthusiast84'),
       ('petlover76'),
       ('sunsetchaser59'),
       ('wanderlust27'),
       ('coffeeaddict85'),
       ('daydreamer71'),
       ('happygolucky33'),
       ('yogi123'),
        ('mysterysolver66');


INSERT INTO PEDIDOS(fecha, monto, id_usuario, id_libro) VALUES
       ('2024-01-15', 23000.00, 5, 18),
       ('2024-01-02', 16000.00, 1, 10),
       ('2024-01-29', 21500.00, 30, 16),
       ('2024-01-10', 25000.00, 10, 17),
       ('2024-01-25', 20000.00, 25, 2),
       ('2024-01-23', 20500.00, 23, 18),
       ('2024-01-06', 15500.00, 6, 1),
       ('2024-01-21', 19000.00, 21, 12),
       ('2024-01-17', 17500.00, 17, 13),
       ('2024-01-14', 22000.00, 14, 13),
       ('2024-01-28', 19500.00, 28, 18),
       ('2024-01-03', 14500.00, 3, 15),
       ('2024-01-12', 25000.00, 12, 2),
       ('2024-01-08', 24000.00, 8, 11),
       ('2024-01-30', 18500.00, 30, 3),
       ('2024-01-11', 15000.00, 11, 18),
       ('2024-01-07', 17500.00, 7, 7),
       ('2024-01-05', 17500.00, 5, 18),
       ('2024-01-16', 22000.00, 16, 18),
       ('2024-01-19', 16000.00, 19, 8),
       ('2024-01-24', 23000.00, 24, 9),
       ('2024-01-26', 19500.00, 26, 2),
       ('2024-01-20', 15000.00, 20, 18),
       ('2024-01-18', 21500.00, 18, 3),
       ('2024-01-27', 20500.00, 27, 18),
       ('2024-01-09', 15500.00, 9, 16),
       ('2024-01-01', 18000.00, 1, 5),
       ('2024-01-04', 25000.00, 4, 18),
       ('2024-01-22', 19500.00, 22, 18),
       ('2024-01-13', 25000.00, 13, 7);


INSERT INTO COMENTARIOS (id_libro, id_usuario, comentario) VALUES
    (1, 6, 'Una lectura obligatoria para aquellos interesados en la física y la vida del famoso científico.'),
    (2, 12, 'Libro desafiante y polemico'),
    (3, 18, 'Recomendado junto con "de animales a dioses"'),
    (9, 24, 'Un libro esencial para comprender la teoría de la evolución y su impacto en la biología.'),
    (3, 30, 'Una obra brillante que desafía nuestras ideas preconcebidas sobre la naturaleza humana.'),
    (5, 1, 'Feliz con mi adquisicion!'),
    (7, 7, 'Este libro me dejó sin palabras, Hawking logra explicar conceptos difíciles de manera simple y emocionante.'),
    (2, 25, 'Una lectura fascinante que te lleva en un viaje a través de la historia de la humanidad.'),
    (11, 8, 'Una lectura que despierta preguntas y reflexiones sobre el sentido de la vida.'),
    (13, 14, 'Me encantó este libro, Platón ofrece una visión utópica de la sociedad y la justicia.'),
    (18, 20, 'Gran libro, me ayudó a encontrar paz interior y claridad mental.'),
    (2, 26, 'Un análisis provocativo y estimulante de la mente humana.'),
    (16, 9, 'Gran libro');
